### ISSUE TITLE
Formattér .txt filer

### ISSUE THREAD

**Issue by KasperOlesen** [cph-ockk/SoftwareDevExamProject#6]

**Comment by KasperOlesen** [comment]
Vi ønsker at formattere alle .txt filerne én gang til at starte med, ud fra følgene template:
FILENAME: Guthenberg-ID
Title: {TITLE}
Author: {author}
Cities: {copenhagen, copenhagen, copenhagen, varde, esbjerg}

**Comment by KPont** [comment]
Er lavet, dog et lidt andet format som diskuteret
